### ISSUE TITLE
[PORN]

### ISSUE THREAD

**Issue by crssi** [Clefspeare13/pornhosts#145]
babes.com
brazzerscontent.com
hdpornhub.co
homemadegirlsporn.com
hotgaylist.com
icfcdn.com
mojoporntube.com
mypornhub.com
peeperz.com
phncdn.com
playboytv.com
pornflip.com
pornhub.net.co
pornhubuk.com
porniq.com
pornoscraper.com
pubnub.com
sexdesant.com
sextube.com
skipthegames.com
txxxsite.com
wareporn.com
whynotbi.com
xnxxii.com
xvideos-cdn.com
younggirlsfreeporn.com

**Comment by spirillen** [comment]
Did you notice the nice submit template, that have been added? It is there for a reason....

So please use the template or wait for @Clefspeare13 to comes around.

**Comment by crssi** [comment]
You should much much simplify the mentioned template. TL/DR

Do whatever you wish. If issue will be treated in normal time frame then I will be happy to add some more in the future.

Cheers ❤️

**Comment by spirillen** [comment]
If you use the templates for either issue or PR well, then I (@spirillen ) will merge stuff typically a couple of times a week.

The reason for this is I simply doesn't have the time to both maintain www.mypdns.org and verify these bulk lists without any documentations. That's why I have been generating these templates, they contain all needed information for quick decisions.

I made little quick guide to add cross refference stuff via uBlock Origin to @DaniV5 

https://github.com/Import-External-Sources/pornhosts/issues/723

**Comment by crssi** [comment]
I will not post a picture of porn, not here, not anywhere.
Documentation or not, do you believe everyone?
I could post issue with an URL and a fake porn site picture and you say you would not double check? I  very doubt it, otherwise this list would be unreliable for any user.
So it doesn't matter for "documentation"... and at the end you will need to open the URLs to check it yourself anyway.
You can use for example extension [URLs List](https://addons.mozilla.org/en-US/firefox/addon/urls-list/), copy/paste the list into and see it yourself in blink of an eye.

So the template at the end is just a waste of issuer and also yours precious time.
I would ask you to really reconsider such demands and please, do not respond to this post immediately, sleep it over once or twice. 

Cheers ❤️

**Comment by DaniV5** [comment]
I thought the same but it's not that simple
its really necessary to document everything we can about the address

**Comment by spirillen** [comment]
That is your choice @crssi, but as mentioned earlier this thread, I'll be happy to merge/add your submission if you follow the examples from @DaniV5 

And here is the important thing you need to remember, THIS repo is @Clefspeare13's not mine, I'm only here as Santa's little helper.

> I could post issue with an URL and a fake porn site picture

Sure, but how many times do you think anyone would trust your submission then?

> So it doesn't matter for "documentation"...

Well it does, try figure out why `sergeproulx.info` have been added and why... (oh yeah right, you wouldn't visit porn sites, so here is the link to the issue <https://gitlab.com/my-privacy-dns/matrix/matrix/-/issues/432> (SFW) :yum: 

> and at the end you will need to open the URLs to check it yourself anyway.

So you would make so many bad submissions, that there would never be to a trust relation?

And why should either I or anyone else who finds the issue have to revisit a domain if all needed documentation is in place?
Remember other might as well use the same issue/PR for there own purpose?

Example:
<https://github.com/Import-External-Sources/pornhosts/pull/784>. Now all I had to do, is to cross reference it in the merge message <https://github.com/Clefspeare13/pornhosts/commit/1ef06038ff2d36a0924463fda66da941ae74ebbc>

At the end, you'll find this approach useful in a couple of years :smiley: when you try to figure out why something was added or removed (ex: https://github.com/Clefspeare13/pornhosts/issues/116 `fastpi.ru` or <https://github.com/Clefspeare13/pornhosts/issues/120> `rapisgator.net`)

At the end it is your choice, if I should commit your contributions, they should be straight forward, otherwise I'll leave them to @Clefspeare13 to handle.
