### ISSUE TITLE
A separate file containing only root domains and not subdomains

### ISSUE THREAD

**Issue by molink36** [Clefspeare13/pornhosts#361]
It would be great if there was a separate file for root domains whose all subdomains can be considered a porn website, and another list for the case which only specific domains from a root domain can be considered a porn website. For example the following:

```
18teenboysex.com
www.18teenboysex.com
cdn.18teenboysex.com
```

Instead of blocking each subdomain separately, all possible subdomains can be blocked using `wildcard` or `regular expression`:

1. Using wildcard:

```
*18teenboysex.com
```

2. Or even better, using regular expression:

```
regexp:^(.*)?18teenboysex\.com$
```

**Comment by spirillen** [comment]
Hey @molink36 what you are speaking of is simply the [Porn Records](https://mypdns.org/my-privacy-dns/porn-records) project :+1: 

That project have it's files divided with you suggestion or need in mind. And for everyone else, here is the little "matrix" of how to combine the source files into a personal BlackList: https://mypdns.org/my-privacy-dns/porn-records#combining-the-lists

The only thing that will not be maintained by @spirillen or @AnonymousPoster is the `mobile.txt`

Is the !!Porn Records!! project what you are asking for?

-------


And for your regex it should be

```java
(^|\.)example\.org$
```

Explanation: 
`()` = Group rule, match one of...
`^` = start with 
`|` = OR
`\.` = literally a dot

Otherwise you would also have a match on  `good-example.org` :smirk:

**Comment by molink36** [comment]
Dear @spirillen
Thank you.
What you suggested was exactly what I was looking for. I needed `wildcard.list`.
