### ISSUE TITLE
How do I contribute?

### ISSUE THREAD

**Issue by pornblocking** [Clefspeare13/pornhosts#90]
Hi,

I really like this repo and want to contribute. I am able to add many more subdomains and sites.

Do I just add them to each hosts file and then run `remove_duplicate_lines.py`? Because I see that everything is in alphabetic order.

Would be nice if you added instructions to the readme.md on how to contribute.

**Comment by spirillen** [comment]
Hi @pornblocking thanks for your interest in contributing. 

So how to contribute. This will be put into 3 answers
1.  The current way
1.  The best way
1.  The future way, If @Clefspeare13 approves my suggestions of improvement in https://github.com/Import-External-Sources/pornhosts (still have a few bugs that needs to be solved.)

## The current way
Yes you simply add all your domains one by one into each of the hosts file.

I use this bash script for that. (Beta version)

`ad_hosts.sh`
```
#!/usr/bin/env bash

# Copyright: https://www.mypdns.org/
# Content: https://www.mypdns.org/p/Spirillen/
# Source: https://github.com/Clefspeare13/pornhosts
# License: https://www.mypdns.org/w/License
# License Comment: GNU AGPLv3, MODIFIED FOR NON COMMERCIAL USE
#
# License in short:
# You are free to copy and distribute this file for non-commercial uses,
# as long the original URL and attribution is included.
#
# Please forward any additions, corrections or comments by logging an
# issue at https://www.mypdns.org/maniphest/

set -e
#set -x

# This Script is only to commit new domains only one ad the time

printf "\nNext porno domain issues\n\n"

read -p "Enter domain to handle as 'domain.tld': " domain

read -p "Enter Clefspeare13 Pornhost Issue ID: " issue

printf "\nAdding domain: $domain\n"
printf "0.0.0.0 $domain\n" >> "0.0.0.0/hosts"
printf "127.0.0.1 $domain\n" >> "127.0.0.1/hosts"
printf "0.0.0.0 $domain\n" >> "Mobile_0_0_0_0/hosts"
printf "0.0.0.0 $domain\n" >> "SafeSearch/hosts"

printf "\nGit commit $domain\nwith Pornhost issue ID: $issue\n"

git commit -am "Adding new porno domain \`${domain}\`

Closes https://github.com/Clefspeare13/pornhosts/issues/${issue}
"
```
For you question about the order, that doesn't matter as is that is sorted with PyFunceble by @funilrys 

Next part is the actual contributing part, there is a somewhat guide here https://github.com/Yodatoo/hostfiles/pull/1 , (read it to the bottom)

## The best way
Since a git is the perfect history book, the optimal way is for each domain you'll add enough information to the issue/PR to have a proper history of why a contribution is: 
1.  Which to be added and confirmed without a secondary lookup for confirmation. 
1.  Reason for adding the submission.
1.  Enough information for other to see why this domain was added 3 years ago, and nobody can remember it.
1.  Submit one domain per issue/PR. for example use this template https://github.com/Import-External-Sources/pornhosts/edit/master/.github/ISSUE_TEMPLATE/default.md
1.  Add it secondary to https://github.com/Import-External-Sources/pornhosts/ in a wild-carded format. ex: `porndomain.com + www.porndomain.com + cdn.porndomain.com` becomes `porndomain.com + *.porndomain.com`

## The future
IF @Clefspeare13 approves my suggestions (in previous mentioned repo) then you still follows the "The Best Way" but you would only need to submit you the domain once in a file as it should be able to add your contribution for 3 projects. 1. This repo, 2. My repo and 3 the rpz zone adult.mypdns.cloud + creating a proper link to origin of contribution and to whom. 3. Automatically take a screenshot for prove :thinking:  But this is in future.....
My idea to this approach is inspired by EasyList repo.

## End note
All the above is currently a bit time consuming vs. what else is being seen on this kind of lists, however, `@nobody` is able to remember why they added anything 2 or 5 years ago. This approach also adding a better option to challenging a suggestion for submission and verify same.

### About README
I'll leave this to @Clefspeare13 to decide whether this should be added or not or put on hold.

Please feel free to ask more questions, together we are strongest. :muscle:

**Comment by pornblocking** [comment]
@spirillen Thanks for the detailed comment. 

Can I just append this to each hosts file?
```
0.0.0.0 porndomain.com
0.0.0.0 www.porndomain.com
```

Of course 127.0.0.1 for windows

**Comment by spirillen** [comment]
Yep, but please do everyone the favor of also provide the why and vary preferably a screenshot. (It would relieve us from a manual lookup in our own browser)

A history (commit) book is not to much use if every chapters only contains the title :smiling_imp: 

And a little note, only add the one that have rel interest. See this thread about `www.` vs `non www.` that https://github.com/Clefspeare13/pornhosts/issues/12

**Comment by funilrys** [comment]
@spirillen maybe a contribution guideline may help!

You could also provide a `commit.template`. [Read more about it](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) (scroll down to `commit.message`)

**Comment by spirillen** [comment]
Hi @funilrys That would be up to @Clefspeare13 to decide, but a very good point which as already have in mind for a later PR... working on some issue templates right now.

Maybe you can remember how to set default reviewers in a PR template... I can't find the line for that

Is it moved to `.github/workflows/`?

https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository
